blank_issues_enabled: false
contact_links:
  - name: Ask the community
    url: https://github.com/alirashidnahal/raid_calculator/discussions/new
    about: Ask and discuss questions with other Raid Calculator community members.
